apiVersion: v1
kind: ConfigMap
metadata:
  name: c4-ecommerce-env
  labels:
    app: c4-ecommerce
data:
  ADDRESS_KAFKA: "my-kafka.message.svc.cluster.local:9092"
  ADDRESS_CUSTOMER: "http://c4-customer:8080"
  PORT: "8080"