apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - virtualservice.yaml
commonLabels:
  app.kubernetes.io/component: c4-notify
  app.kubernetes.io/managed-by: c4
  app.kubernetes.io/part-of: c4
  app.kubernetes.io/version: 0.0.1

configMapGenerator:
- literals:
  name: c4-customer-env