apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment-v1.yaml
  - deployment-v2.yaml
  - service.yaml
  - istio-virtualservice.yaml
  - istio-destinationrule.yaml
commonLabels:
  app.kubernetes.io/component: c4-customer
  app.kubernetes.io/managed-by: c4
  app.kubernetes.io/part-of: c4

configMapGenerator:
- literals:
  name: c4-customer-env