apiVersion: v1
kind: ConfigMap
metadata:
  name: c4-payment-env
  labels:
    app: c4-payment
data:
  ADDRESS_KAFKA: "my-kafka.message.svc.cluster.local:9092"
  MONGO_ADDRS: "mongo-payment-mongodb.database.svc.cluster.local"
  MONGO_DATABASE: "c4-payment-database"
  MONGO_USERNAME: "admin"
  MONGO_PASSWORD: "admin"
  PORT: "8080"