apiVersion: v1
kind: ConfigMap
metadata:
  name: c4-order-env
  labels:
    app: c4-order
data:
  ADDRESS_KAFKA: "my-kafka.message.svc.cluster.local:9092"
  MONGO_ADDRS: "mongo-order-mongodb.database.svc.cluster.local"
  MONGO_DATABASE: "c4-order-database"
  MONGO_USERNAME: "admin"
  MONGO_PASSWORD: "admin"
  PORT: "8080"