apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment-http.yaml
  - deployment-grpc.yaml
  - service-http.yaml
  - service-grpc.yaml
  - istio-http-destinationrule.yaml
  - istio-http-virtualservice.yaml
commonLabels:
  app.kubernetes.io/component: c4-type
  app.kubernetes.io/managed-by: c4
  app.kubernetes.io/part-of: c4

configMapGenerator:
- literals:
  name: c4-type-env