apiVersion: v1
kind: ConfigMap
metadata:
  name: c4-customer-env
  labels:
    app: c4-customer
data:
  ADDRESS_KAFKA: "my-kafka.message.svc.cluster.local:9092"
  POSTGRES_ADDRS: "postgresql://postgres:pgpassword@postgres-postgresql.database.svc.cluster.local:5432?sslmode=disable"
  ADDRESS_TYPE_HTTP: "http://c4-type-http:8080"
  ADDRESS_TYPE_GRPC: "c4-type-grpc:5000"
  PORT: "8080"
